openai_api_key: "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"
gcp_project_id: "vidhra"
google_api_key: "AIzaSyCLA8hwNOpQeE5V0mKTs2LPidXp5Vo8AMs"

rag_docs_path: "./internal/tools/gcloud_online_docs_markdown" # Or your actual path
rag_embedding_model: "text-embedding-004"
vector_store: "chroma"  # Or "duckdb"

# Optional: Define default persistent store paths if not using RAGEngine internal defaults
# These can be overridden by environment variables or CLI args.
# If these are commented out or missing, RAGEngine will use its own internal defaults 
# (e.g., ./db/chroma_db for chroma_path).
chroma_db_path: "./db/chroma_db"
chroma_collection_name: "gclouddocs_main"
duckdb_path: "./db/my_saturn_duckdb_store" # Directory for the .duckdb file
duckdb_file_name: "saturn_vectors.duckdb"
duckdb_table_name: "saturn_embeddings"