[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "saturn"
version = "0.1.0"
description = "A natural language interface for Google Cloud Platform APIs."
authors = [
    { name = "prashanth varma", email = "your.email@example.com" },
]
readme = "README.md" # Optional
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # Choose your license
    "Operating System :: OS Independent",
]
dependencies = [
    "openai>=1.3.0",
    "google-cloud-aiplatform>=1.38.0", # For Gemini
    "anthropic>=0.15.0", # For Claude
    "mistralai>=0.1.0", # For Mistral
    "google-auth>=2.0.0",
    "google-api-python-client>=2.0.0", # May be needed by executor
    # Add specific GCP client libraries as needed by your KB, e.g.:
    "google-cloud>=0.31.0",
    # ---
    "pydantic>=2.0.0",
    "PyYAML>=6.0",
    "python-dotenv>=1.0.0",
    "typer[all]>=0.9.0",
    "json-repair>=0.19.0",
    "rich>=13.0.0"
]

[project.urls] # Optional
"Homepage" = "https://github.com/vidhra/Saturn"
"Bug Tracker" = "https://github.com/vidhar/Saturn/issues"

# --- Add Script Entry Point --- 
[project.scripts]
saturn = "saturn.cli:app"
# --- End Entry Point --- 

# --- Explicitly define packages to include --- 
[tool.setuptools.packages.find]
include = ["saturn*", "model", "internal"] # Made model and internal more specific
exclude = ["tests*", "venv*", "embeddings_env*"] # Exclude tests, venv, etc.